### ISSUE TITLE
Document image editing API

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_apidoc#11]
Someone accidentally uploaded a *thousand* photos with inaccurate GPS coordinates (time offset between camera and gpx logger). This should be fixable by getting the correct coordinates from the gpx and doing an "edit" on the photos, but it's obviously impractical to do manually.

I need documentation on the API used by the /map/e/:id webpage to do change requests, so I can write a script that mass-edits the GPS coordinates of this giant sequence. (I also need assurance that the 'change request' will be 'approved' some day...)

**Comment by gyllen** [comment]
A new changeset API is under construction to enable you to do exactly this. The problem with the API used in /map/e/:id is that its not designed for the scale of uploads we have today. 

@peterneubauer is actively working on this and its scheduled to be released early 2016.
