### ISSUE TITLE
Authentication/Credentials API missing

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_apidoc#13]
The documentation is missing API requests for user authentication or passing user credentials to Mapillary. OAuth 2.0 is good, even very good. However, it has been designed primarily with web browsers in mind. And, although the OAuth 2.0 specification mentions client authentication via basic HTTP authentication with credentials like user name and password, it advises against this practice for security reasons. So, how should applications enable users to authenticate with their Mapillary credentials which can not or do not want to rely on an external browser?

**Comment by gyllen** [comment]
@GITNE I don't see this as an issue. OAuth 2.0 is widely accepted as the method to act on behalf of a user on another platforms. Its used by any bigger platform out there.

We do not support the password flow for exactly the reason you give, its not secure, and you do not want users to have to pass a password through a third party app.

For example the Oauth 2.0 flow in JOSM has already been solved by our excellent summer of code worker Jorge.

**Comment by GITNE** [comment]
> For example the Oauth 2.0 flow in JOSM has already been solved by our excellent summer of code worker Jorge.

Yes and no. Only receiving the oauth code via a redirect has been sort of solved. And then only sort of because it assumes that the application can always open a listening port, which may not always be allowed by a system admin* (for whatever good reasons). And definitely not because it still requires or relies on an external browser for authentication. So, your system **MUST** have a web browser installed (with working MIME and protocol handlers), which is a **strange** requirement you are imposing on third party apps.


*Yes, the admin /can/ explicitly allow to open a specific listening port to a specific app. However, this something most admins would really like to avoid, which is a topic of its own.

**Comment by gyllen** [comment]
As I stated above every major platform uses OAuth 2.0 on any device that needs third party login, we are NOT going to invent something new.

We are also NOT opening up password login for third party apps for security reasons.

**Comment by GITNE** [comment]
I get the impression that we are talking to each other while missing the point.

> As I stated above every major platform uses OAuth 2.0 on any device that needs third party login, we are NOT going to invent something new.

I did not demand or request to abandon OAuth 2.0. I even said that it is good that you support it. And, I definitely did not suggest to invent anything new. So, please keep supporting OAuth 2.0. Hence, OAuth 2.0 is not the point.
 
> We are also NOT opening up password login for third party apps for security reasons.

Now, here is the point because you sort of already have done that. Password log-in is available on the website. The only problem with that for third party developers is that they would need to reverse engineer this process and then build into their apps. Which is just a stupid waste of resources.

Believe me, there is no security gain or loss if credentials are read by any third party app and then passed through via HTTPS to any authentication server (yes, even if the app is malicious). It is on the authentication server (and protocol) to be properly and securely implemented. Having the credential authentication protocol open would just make the life of users easier and remove awkward dependencies.

If you do not believe me, just look at any Twitter or Facebook app. Or, OpenStreetMap and JOSM. It is exactly the same concept. But, to have it work seamlessly you have to document the authentication (or credential) passing protocol.

**Comment by gyllen** [comment]
You miss the point that if you put your password into a third party app, then that app can save your password or even worse send it somewhere else.

**Comment by GITNE** [comment]
> You miss the point that if you put your password into a third party app, then that app can save your password or even worse send it somewhere else.

I am sorry but... :laughing: & ROFL So can web pages in browsers or compromised browsers too!

Again, OAuth 2.0 is an **authorization** protocol not an **authentication** protocol. No browser is more or less secure for authentication than any other app. Authentication security does not come from any particular client, it comes from a properly implemented **authentication** **protocol**.

**Comment by gyllen** [comment]
When you start arguing against the very fundamentals of the internet (i.e. the browsers), thats when the discussion ends.... ;)

**Comment by GITNE** [comment]
:neutral_face: :palm_tree: The very fundamentals of the internet are **protocols** not browsers.

Before you answer, go home, think about it, maybe even a couple of days, sleep over it, and the enlightenment will come to you.

**Comment by gyllen** [comment]
This discussion has way left the topic it started at. Im locking.
