### ISSUE TITLE
Client ID (Application settings) page does not exist

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_apidoc#7]
The API documentation starts off by stating you need a Client ID to use the API, and has a link "application settings page" that points to http://www.mapillary.com/map/settings/applications.

However, that page does not exist.

**Comment by jesolem** [comment]
thanks @pbb72

**Comment by pbb72** [comment]
Hmm, either the change is not live yet, or there is several pages that contain the bad link. I am talking about the link on https://a.mapillary.com/#client_id. If it will just take a while before the change is live, you shouldn't close the bug until it is. (For example because someone else might report the same problem, not seeing the closed bug report.)

**Comment by jesolem** [comment]
@pbb72 Sorry, seems this was not deployed yet.
