### ISSUE TITLE
Get list all user's name in country

### ISSUE THREAD

**Issue by spatialhast** [mapillary/mapillary_apidoc#9]
Hi Mapillary team,

I use https://a.mapillary.com/#get-statsimtoplist to get list all user's name in Ukraine (url https://a.mapillary.com/v2/stats/toplist?client_id=MYID&cname=ukraine), but in 'total' key of JSON I receive not all list of users in Ukraine? for example in 'toplist' exists users 'sanjak, vsviridov' but they not exist in 'total' key of JSON. Please help me receive list of all Mapillary users in Ukraine.

Thanks!

**Comment by gyllen** [comment]
Hi @spatialhast try adding the parameter limit=X to the call, .i.e. https://a.mapillary.com/v2/stats/toplist?client_id=MYID&cname=ukraine&limit=100

**Comment by gyllen** [comment]
Also a headsup this API will soon be deprecated for a one with more accurate borders. Stay tuned for that update.

**Comment by spatialhast** [comment]
@gyllen Thx :+1:
